name: Generate Pac-Man Contributions

on:
  schedule:
    - cron: "0 */6 * * *" # Roda a cada 6 horas
  workflow_dispatch:      # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate Pac-Man Grid
        run: python main.py
      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/*
          git commit -m "Update Pac-Man grid"
          git push
